# Generated by Django 2.2.10 on 2020-03-21 18:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200321_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete='auth.User', to=settings.AUTH_USER_MODEL),
        ),
    ]
