# Generated by Django 2.2.10 on 2020-04-30 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200424_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='executor',
            field=models.ManyToManyField(blank=True, null=True, to='core.Profile'),
        ),
    ]
