# Generated by Django 2.2.10 on 2020-04-10 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_auto_20200322_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='executor',
            field=models.ManyToManyField(blank=True, to='mainpage.Profile'),
        ),
    ]
